name: build

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    defaults:
     run:
       shell: bash

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build -DBUILD_TESTS=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run:  cmake --build .

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V
